---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
exclude_paths:
- tests/
- docs/
- ucsmsdk/mometa/
- ucsmsdk/methodmeta/
